import ajax from './ajax'
export const login = (formData) => ajax("/login",formData,"POST")
export const category = (parentId=0) => ajax('/manage/category/list',{parentId},"GET") 
export const addCategory = (categoryName, parentId=0) => ajax('/manage/category/add',{categoryName,parentId},"POST") 
export const updateCategory = (categoryId, categoryName) => ajax('/manage/category/update',{categoryId,categoryName},"POST") 
export const productList = (pageNum, pageSize) => ajax('/manage/product/list',{pageNum,pageSize},'GET')
export const categoryinfo = (categoryId) => ajax('/manage/category/info',{categoryId},'GET')
export const searchProduct = (pageNum, pageSize, searchName, searchType) => ajax('/manage/product/search',{pageNum,pageSize,[searchType]:searchName},'GET')
export const updateStatus = (productId, status)=> ajax('/manage/product/updateStatus',{productId, status},'POST')
export const addProduct = (productFormData) => ajax('/manage/product/add',productFormData,'POST')
export const updateProduct = (updateProductFormData) => ajax('/manage/product/update',updateProductFormData,'POST')
export const getUserList = () => ajax('/manage/user/list',{},"GET")
export const addRole = (roleName) => ajax('/manage/role/add',roleName,"POST")
export const roleUpdate = (roleUpdateData) => ajax('/manage/role/update',roleUpdateData,"POST")
export const addUser = (addUserFormData) => ajax('/manage/user/add',addUserFormData,"POST")
export const updateUser =(updateUserFormData) => ajax('/manage/user/update',updateUserFormData,"POST")
export const deleteUser = (id) => ajax('/manage/user/delete',id,"POST")